default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password:
  encoding: utf8

development:
  <<: *default
  database: khdevconf_development

test:
  <<: *default
  database: khdevconf_test

production:
  <<: *default
  database: khdevconf_production
  username: khdevconf
  password: <%= ENV['KHDEVCONF_DATABASE_PASSWORD'] %>
